### ISSUE TITLE
says token is invalid

### ISSUE THREAD

**Issue by Toastyisburning** [aaronr5tv/BigBenBot#1]
i have been trying to get this working and i keep getting the same error, my token is grabbed directly from dev portal and still nothing
![image](https://user-images.githubusercontent.com/50493368/123264043-a367c780-d4c7-11eb-8c0c-cd80e29d82f5.png)

**Comment by Toastyisburning** [comment]
`(my token)=your token here
(guild id)=your guild id here
(vc)=voice channel id here
TEXT_CHANNEL_ID=text channel id here(this is opt leave it like this or delete it if you do not care about chat messages)`
i wrote it like this and the opposite way around and i keep getting this same error

**Comment by aaronr5tv** [comment]
Your token and id's should go on the right side of the = not the left. Also make sure your '.env' file isn't actually a .txt file with the extension hidden. It has to be a valid environment file.

**Comment by Toastyisburning** [comment]
i still get the same error when i do that, is there a different name it should be called (not the file extention)

**Comment by aaronr5tv** [comment]
Not sure man. Your file should just be named `.env` thats the entire name. and it will show up as type ENV in your file explorer on windows. If configured properly it will work, there's a number of mistakes you could be making but without actually seeing your files I can't do much.

**Comment by Toastyisburning** [comment]
https://drive.google.com/drive/folders/1rDr7Jxor6dFdol80Lbemwa3AagJgXjK4?usp=sharing
heres a link to my files, (with the token and other details taken out)

**Comment by aaronr5tv** [comment]
@JustToasty Okay so the file should just be called `.env` not `file.env`. I know it can be confusing and seem weird to name a file just `.env` if you aren't familiar with setting up environment variables but thats just the file the system looks for when reading env variables so if you don't have it named properly it won't work.

**Comment by Toastyisburning** [comment]
Ok, i got it working. Honestly thought it was weird that you didn't specify a name but that makes sense, thanks for your help.
